<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Magento\Framework\Escaper $escaper */
/** @var Sigma\Blog\ViewModel\Post $postVm */

$postVm = $block->getData('post_vm');
$post = $postVm->getDetail();
?>
<div class="blog-post-detail">
    <h><?= $escaper->escapeHtml($post->getTile()) ?></h>
    <P><?= $escaper->escapeHtml($post->getContent(), ['em','p','strong']) ?></P>
</div>

