<?php
/**
 * @var Magento\Framework\View\Element\Template $block
 */
?>

<div class="Other-">
    <p><strong> <?= __('Blog Post Sidebar') ?> </strong></p>
    <ul>
        <li><a href=" <?= $block->getUrl('blog/post/detail', ['id' => 1])  ?>">Post 1</a></li>
        <li><a href=" <?= $block->getUrl('blog/post/detail', ['id' => 2])  ?>">Post 2</a></li>
        <li><a href=" <?= $block->getUrl('blog/post/detail', ['id' => 3])  ?>">Post 3</a></li>
        <p><?= __("Post count: %1",3) ?></p>
    </ul>
</div>